import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {supabase} from "./supabase";
import "./styles.css";
const PHONE="918125552523", money=n=>"₹"+Number(n).toLocaleString("en-IN");
function App(){
 const [products,setProducts]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [q,setQ]=useState(""),[brand,setBrand]=useState("All"),[available,setAvailable]=useState(false),[sort,setSort]=useState("featured");
 useEffect(()=>{(async()=>{const {data,error}=await supabase.from("mobiles").select("*").order("created_at",{ascending:false});if(error)setError(error.message);else setProducts(data||[]);setLoading(false)})()},[]);
 const brands=useMemo(()=>["All",...new Set(products.map(x=>x.brand).filter(Boolean))],[products]);
 const list=useMemo(()=>{let a=products.filter(p=>(`${p.brand||""} ${p.model||""} ${p.ram||""} ${p.storage||""} ${p.color||""}`).toLowerCase().includes(q.toLowerCase())&&(brand==="All"||p.brand===brand)&&(!available||p.stock));if(sort==="low")a.sort((x,y)=>Number(x.price)-Number(y.price));if(sort==="high")a.sort((x,y)=>Number(y.price)-Number(x.price));return a},[products,q,brand,available,sort]);
 const ask=p=>window.open(`https://wa.me/${PHONE}?text=${encodeURIComponent(`Hi Bhanu Mobile Plaza, I am interested in ${p.brand} ${p.model} (${p.ram||""} ${p.storage||""}) priced at ${money(p.price)}. Is it available?`)}`,"_blank");
 return <div><header className="top"><div className="nav"><div className="logo"><span>BM</span><div><b>Bhanu Mobile Plaza</b><small>SEETHANGARAM</small></div></div><div className="navlinks"><a href="#stock">Stock</a><a href="#contact">Contact</a><a className="wa" href={`https://wa.me/${PHONE}`} target="_blank">WhatsApp</a></div></div></header>
 <section className="hero"><div className="heroText"><div className="pill">📱 YOUR LOCAL MOBILE STORE</div><h1>Find your next<br/><em>smartphone.</em></h1><p>Check our latest mobile stock and prices online before visiting Bhanu Mobile Plaza in Seethangaram.</p><div className="heroBtns"><a href="#stock" className="primary">View available phones ↓</a><a href={`tel:+${PHONE}`} className="secondary">☎ 81255 52523</a></div><div className="trust"><span>✓ Latest models</span><span>✓ Competitive prices</span><span>✓ Local support</span></div></div><div className="heroPhones"><div className="orb"></div><div className="phone p1">S</div><div className="phone p2">1+</div><div className="phone p3">V</div></div></section>
 <main id="stock"><div className="sectionHead"><div><div className="eyebrow">LIVE SHOP STOCK</div><h2>Available mobiles</h2><p>Prices and stock are loaded directly from the shop database.</p></div><strong>{loading?"Loading…":`${list.length} models`}</strong></div>
 <div className="controls"><div className="search">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search phone or brand..."/></div><select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Sort: Featured</option><option value="low">Price: Low to high</option><option value="high">Price: High to low</option></select></div>
 <div className="chips">{brands.map(b=><button className={brand===b?"chip on":"chip"} onClick={()=>setBrand(b)} key={b}>{b}</button>)}<label className="check"><input type="checkbox" checked={available} onChange={e=>setAvailable(e.target.checked)}/> Available only</label></div>
 {loading&&<div className="empty">Loading current stock…</div>}{error&&<div className="error">Unable to load stock: {error}</div>}
 {!loading&&!error&&<div className="grid">{list.map(p=><article className="card" key={p.id}><div className="image">{p.image_url?<img src={p.image_url} alt={`${p.brand} ${p.model}`}/>:<div className="device"><span>{(p.brand||"M").slice(0,2)}</span></div>}<span className={p.stock?"dot availableDot":"dot outDot"}>{p.stock?"Available":"Out of stock"}</span></div><div className="body"><div className="brand">{p.brand}</div><h3>{p.model}</h3><p>{[p.ram,p.storage].filter(Boolean).join(" • ")}</p>{p.color&&<p>{p.color}</p>}<div className="price">{money(p.price)}</div><button disabled={!p.stock} onClick={()=>ask(p)}>{p.stock?"💬 Enquire on WhatsApp":"Currently unavailable"}</button></div></article>)}</div>}
 {!loading&&!error&&!list.length&&<div className="empty">No matching phones found.</div>}</main>
 <section className="contact" id="contact"><div><div className="eyebrow">VISIT OUR SHOP</div><h2>Bhanu Mobile Plaza</h2><p>📍 Seethangaram</p><p>📞 81255 52523</p></div><div className="contactBtns"><a href={`https://wa.me/${PHONE}`} target="_blank">WhatsApp us</a><a href="https://www.google.com/maps/search/?api=1&query=Bhanu+Mobile+Plaza+Seethangaram" target="_blank">Open Maps ↗</a></div></section><footer><b>Bhanu Mobile Plaza</b><span>Seethangaram · 81255 52523</span><small>© 2026 Bhanu Mobile Plaza</small></footer></div>
}
createRoot(document.getElementById("root")).render(<App/>);